cryptnox-sdk-arduino: examples/BasicUsage/BasicUsage.ino File Reference
BasicUsage.ino File Reference
#include <CryptnoxWallet.h>
#include <SPI.h>
Macros
#define USE_SPI
#define PN532_SS (10U)
SPI slave select (CS) pin for the PN532 module.
#define DEFAULT_PIN "000000000"
Default PIN code (ASCII digits). Must match the PIN used during card.init().
#define DEFAULT_PIN_LEN (sizeof(DEFAULT_PIN) - 1U)
Functions
PN532Adapter nfc (serialAdapter, PN532_SS, &SPI)
void setup ()
Arduino setup function.
void loop ()
Arduino main loop.
Variables
ArduinoLoggerAdapter serialAdapter
ArduinoCryptoProvider cryptoProvider
ArduinoPlatform platform
CryptnoxWallet wallet (nfc, serialAdapter, cryptoProvider, platform)
Macro Definition Documentation
DEFAULT_PIN
#define DEFAULT_PIN "000000000"
Default PIN code (ASCII digits). Must match the PIN used during card.init().
Examples
BasicUsage.ino.
Definition at line 75 of file BasicUsage.ino.
Referenced by loop().
DEFAULT_PIN_LEN
#define DEFAULT_PIN_LEN (sizeof(DEFAULT_PIN) - 1U)
Examples
BasicUsage.ino.
Definition at line 76 of file BasicUsage.ino.
Referenced by loop().
PN532_SS
#define PN532_SS (10U)
SPI slave select (CS) pin for the PN532 module.
Examples
BasicUsage.ino.
Definition at line 39 of file BasicUsage.ino.
Referenced by nfc().
USE_SPI
#define USE_SPI
Definition at line 25 of file BasicUsage.ino.
Function Documentation
loop()
void loop ()
Arduino main loop.
Demonstrates simplified card connection and processing:
Connect to card and establish secure channel (combines detection and channel setup)
Sign a test hash (PIN included in sign payload)
Clear session and reset reader
Examples
BasicUsage.ino, Connect.ino, Sign.ino, UsdcSigning.ino, and VerifyPin.ino.
Definition at line 117 of file BasicUsage.ino.
References CW_HASH_SIZE, CW_OK, CW_SIG_R_OFFSET, CW_SIG_S_OFFSET, CW_SIGN_CURR_K1, CW_SIGN_SIG_ECDSA_LOW_S, CW_SIGN_WITH_PIN, DEFAULT_PIN, DEFAULT_PIN_LEN, CW_SignResult::errorCode, F, CW_SignRequest::hash, CW_SignRequest::hashLength, HEX, CW_SignRequest::pin, CW_Utils::safe_memcpy(), CW_Utils::secure_wipe(), serialAdapter, CW_SignResult::signature, and wallet.
nfc()
PN532Adapter nfc (serialAdapter , PN532_SS , & SPI)
Examples
BasicUsage.ino, Connect.ino, Sign.ino, UsdcSigning.ino, and VerifyPin.ino.
References PN532_SS, and serialAdapter.
Referenced by setup().
setup()
void setup ()
Arduino setup function.
Initializes the serial port for debugging, the selected bus, and the PN532 module.
Examples
BasicUsage.ino, Connect.ino, Sign.ino, UsdcSigning.ino, and VerifyPin.ino.
Definition at line 88 of file BasicUsage.ino.
References F, serialAdapter, and wallet.
Variable Documentation
cryptoProvider
ArduinoCryptoProvider cryptoProvider
Examples
BasicUsage.ino, Connect.ino, Sign.ino, UsdcSigning.ino, and VerifyPin.ino.
Definition at line 78 of file BasicUsage.ino.
platform
ArduinoPlatform platform
Examples
BasicUsage.ino, Connect.ino, Sign.ino, UsdcSigning.ino, and VerifyPin.ino.
Definition at line 79 of file BasicUsage.ino.
Referenced by CryptnoxWallet::CryptnoxWallet(), and CW_SecureChannel::CW_SecureChannel().
serialAdapter
ArduinoLoggerAdapter serialAdapter
Examples
BasicUsage.ino, Connect.ino, Sign.ino, UsdcSigning.ino, and VerifyPin.ino.
Definition at line 47 of file BasicUsage.ino.
Referenced by loop(), nfc(), nfc(), and setup().
wallet
CryptnoxWallet wallet(nfc, serialAdapter, cryptoProvider, platform) (nfc , serialAdapter , cryptoProvider , platform)
Examples
BasicUsage.ino, Connect.ino, Sign.ino, UsdcSigning.ino, and VerifyPin.ino.
Referenced by loop(), and setup().