cryptnox-sdk-arduino: NullLoggerAdapter Class Reference
NullLoggerAdapter Class Reference
Arduino concrete adapters
No-op CW_Logger — guarantees nothing reaches the serial port.
#include <NullLoggerAdapter.h>
Public Member Functions
NullLoggerAdapter ()=default
~NullLoggerAdapter () override=default
NullLoggerAdapter (const NullLoggerAdapter &)=delete
NullLoggerAdapter & operator= (const NullLoggerAdapter &)=delete
bool begin (unsigned long=115200UL) override
No-op begin(); returns true to match the interface contract.
void print (const __FlashStringHelper *) override
No-op.
void print (const char *) override
No-op.
void print (char) override
No-op.
void print (uint8_t, int=DEC) override
No-op.
void print (uint16_t, int=DEC) override
No-op.
void print (uint32_t, int=DEC) override
No-op.
void print (int, int=DEC) override
No-op.
void println () override
No-op.
void println (const __FlashStringHelper *) override
No-op.
void println (const char *) override
No-op.
void println (char) override
No-op.
void println (uint8_t, int=DEC) override
No-op.
void println (uint16_t, int=DEC) override
No-op.
void println (uint32_t, int=DEC) override
No-op.
void println (int, int=DEC) override
No-op.
Public Member Functions inherited from CW_Logger
virtual ~CW_Logger ()
Detailed Description
No-op CW_Logger — guarantees nothing reaches the serial port.
Every CW_Logger method is an empty inline override, so:
The compiler dead-code-eliminates the formatting work at the call site (no string format, no hex conversion, no Serial write).
Even with CW_DEBUG_LOGGING enabled in the build, no APDU contents, no session-key fragments, no PIN-handling traces leave the chip through the UART (audit findings LOW-03 / MED-02).
Required for any deployment where a physically accessible UART must not become a side-channel.
Example — production wiring
NullLoggerAdapter     logger;             // silent
ArduinoCryptoProvider crypto;
PN532Adapter          nfc(logger, 10);
CryptnoxWallet        wallet(nfc, logger, crypto, platform);
Note
Drop-in interchangeable with ArduinoLoggerAdapter — flip the one declaration line to switch between dev and production builds.
Definition at line 50 of file NullLoggerAdapter.h.
Constructor & Destructor Documentation
NullLoggerAdapter() [1/2]
NullLoggerAdapter::NullLoggerAdapter () default
Referenced by NullLoggerAdapter(), and operator=().
~NullLoggerAdapter()
NullLoggerAdapter::~NullLoggerAdapter () override default
NullLoggerAdapter() [2/2]
NullLoggerAdapter::NullLoggerAdapter (const NullLoggerAdapter &) delete
References NullLoggerAdapter().
Member Function Documentation
begin()
bool NullLoggerAdapter::begin (unsigned long = 115200UL) inline override virtual
No-op begin(); returns true to match the interface contract.
Implements CW_Logger.
Definition at line 59 of file NullLoggerAdapter.h.
operator=()
NullLoggerAdapter & NullLoggerAdapter::operator= (const NullLoggerAdapter &) delete
References NullLoggerAdapter().
print() [1/7]
void NullLoggerAdapter::print (char) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 63 of file NullLoggerAdapter.h.
print() [2/7]
void NullLoggerAdapter::print (const __FlashStringHelper *) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 61 of file NullLoggerAdapter.h.
print() [3/7]
void NullLoggerAdapter::print (const char *) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 62 of file NullLoggerAdapter.h.
print() [4/7]
void NullLoggerAdapter::print (int , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 67 of file NullLoggerAdapter.h.
References DEC.
print() [5/7]
void NullLoggerAdapter::print (uint16_t , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 65 of file NullLoggerAdapter.h.
References DEC.
print() [6/7]
void NullLoggerAdapter::print (uint32_t , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 66 of file NullLoggerAdapter.h.
References DEC.
print() [7/7]
void NullLoggerAdapter::print (uint8_t , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 64 of file NullLoggerAdapter.h.
References DEC.
println() [1/8]
void NullLoggerAdapter::println () inline override virtual
No-op.
Implements CW_Logger.
Definition at line 69 of file NullLoggerAdapter.h.
println() [2/8]
void NullLoggerAdapter::println (char) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 72 of file NullLoggerAdapter.h.
println() [3/8]
void NullLoggerAdapter::println (const __FlashStringHelper *) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 70 of file NullLoggerAdapter.h.
println() [4/8]
void NullLoggerAdapter::println (const char *) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 71 of file NullLoggerAdapter.h.
println() [5/8]
void NullLoggerAdapter::println (int , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 76 of file NullLoggerAdapter.h.
References DEC.
println() [6/8]
void NullLoggerAdapter::println (uint16_t , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 74 of file NullLoggerAdapter.h.
References DEC.
println() [7/8]
void NullLoggerAdapter::println (uint32_t , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 75 of file NullLoggerAdapter.h.
References DEC.
println() [8/8]
void NullLoggerAdapter::println (uint8_t , int = DEC) inline override virtual
No-op.
Implements CW_Logger.
Definition at line 73 of file NullLoggerAdapter.h.
References DEC.
The documentation for this class was generated from the following file:
src/NullLoggerAdapter.h