@echo off
REM SPDX-License-Identifier: LGPL-3.0-or-later
REM Copyright (c) 2026 Cryptnox SA
REM
REM Enable memory optimization for the Cryptnox SDK on Arduino UNO R4.
REM
REM Applies three optimizations to the Renesas core install under Arduino15:
REM
REM   1. platform.local.txt with extra compiler flags:
REM        -fno-exceptions -fno-rtti  strip C++ exception/RTTI code (~100 B)
REM        -DuECC_SUPPORTS_*=0        drop unused micro-ecc curves
REM
REM   2. Patch cores/arduino/api/deprecated-avr-comp/avr/dtostrf.c.impl
REM        Removes asm(".global _printf_float") which was hard-pulling the
REM        newlib-nano float printf runtime (~10 KB) even when unused.
REM
REM   3. (Reminder) The AESLib_no_iostream.patch from the project's setup.bat
REM        is what gives the BIG win (~145 KB). Run setup.bat first if you
REM        have not already.
REM
REM NOTE: -flto was tried and rejected. It breaks the link on the Renesas
REM core (weak symbol cm_backtrace_fault and prebuilt trng.a are not handled
REM by the LTO plugin). Do not re-enable -flto.
REM
REM To revert: delete the platform.local.txt AND restore dtostrf.c.impl
REM from the .backup file printed at the end.

setlocal EnableDelayedExpansion

REM Auto-detect the latest installed Renesas core under Arduino15
set "CORE_DIR=%USERPROFILE%\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno"
if not exist "%CORE_DIR%" (
    echo ERROR: Renesas core not installed at:
    echo   %CORE_DIR%
    echo Install "Arduino UNO R4 Boards" via Boards Manager first.
    exit /b 1
)

REM Pick the highest-numbered version subdirectory
set "CORE_VERSION="
for /f "delims=" %%V in ('dir /b /ad "%CORE_DIR%" ^| sort /r') do (
    if not defined CORE_VERSION set "CORE_VERSION=%%V"
)
if not defined CORE_VERSION (
    echo ERROR: No version directory under %CORE_DIR%
    exit /b 1
)

set "PLATFORM_DIR=%CORE_DIR%\%CORE_VERSION%"
set "TARGET=%PLATFORM_DIR%\platform.local.txt"
set "DTOSTRF=%PLATFORM_DIR%\cores\arduino\api\deprecated-avr-comp\avr\dtostrf.c.impl"

echo Renesas core version: %CORE_VERSION%
echo.

REM ---------------------------------------------------------------------------
REM Step 1: Write platform.local.txt
REM ---------------------------------------------------------------------------
echo [1/2] Writing %TARGET%

(
    echo # platform.local.txt - Cryptnox SDK memory optimization
    echo # Generated by scripts/enable_memory_optimization.bat
    echo # To revert: delete this file.
    echo.
    echo compiler.cpp.extra_flags=-fno-exceptions -fno-rtti -DuECC_SUPPORTS_secp160r1=0 -DuECC_SUPPORTS_secp192r1=0 -DuECC_SUPPORTS_secp224r1=0 -DuECC_SUPPORTS_secp256k1=0
    echo compiler.c.extra_flags=-DuECC_SUPPORTS_secp160r1=0 -DuECC_SUPPORTS_secp192r1=0 -DuECC_SUPPORTS_secp224r1=0 -DuECC_SUPPORTS_secp256k1=0
) > "%TARGET%"

if not exist "%TARGET%" (
    echo   ERROR: failed to write %TARGET%
    exit /b 1
)
echo   OK

REM ---------------------------------------------------------------------------
REM Step 2: Patch dtostrf.c.impl
REM ---------------------------------------------------------------------------
echo [2/2] Patching %DTOSTRF%

if not exist "%DTOSTRF%" (
    echo   ERROR: dtostrf.c.impl not found - core layout changed?
    exit /b 1
)

REM Skip if already patched (sentinel string)
findstr /C:"PATCHED: removed" "%DTOSTRF%" >nul 2>&1
if not errorlevel 1 (
    echo   already patched, skipping
    goto :patches_done
)

REM Backup the original
if not exist "%DTOSTRF%.backup" (
    copy /Y "%DTOSTRF%" "%DTOSTRF%.backup" >nul
)

set "SCRIPT_DIR=%~dp0"
set "PATCH_FILE=%SCRIPT_DIR%..\patches\Renesas_core_dtostrf.patch"

if not exist "%PATCH_FILE%" (
    echo   ERROR: patch file not found at:
    echo   %PATCH_FILE%
    exit /b 1
)

REM git apply works from anywhere with --unsafe-paths --directory
pushd "%PLATFORM_DIR%" >nul
git apply --unsafe-paths --directory="%PLATFORM_DIR%" "%PATCH_FILE%" 2>&1
set "PATCH_RC=!errorlevel!"
popd >nul

if !PATCH_RC! neq 0 (
    echo   WARNING: patch failed. Apply manually or check %DTOSTRF%
) else (
    echo   OK
)

:patches_done
echo.
echo ============================================
echo  Memory optimization done. Restart the IDE.
echo ============================================
echo.
echo Expected gain over an un-optimized build:
echo   - AESLib iostream strip (via setup.bat):  ~145 KB
echo   - dtostrf _printf_float removal:            ~10 KB
echo   - C++ runtime + uECC flags:                  ~1 KB
echo.
echo To revert all changes:
echo   del "%TARGET%"
echo   move /Y "%DTOSTRF%.backup" "%DTOSTRF%"

endlocal
exit /b 0
